language: java

jdk:
  - oraclejdk8

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
- mvn test

env:
  global:
    - secure: "dlgfwecL9SPGSW2xDt5DVVrIvLFPCo9lU0PoE+cVzyuYzM3oc9mMvcvLX0sLK+ND/3TAIZmr7ILwzp+KMauHclmtmMAP47m1UW/A1BJ/AQg1ZyX6vXV7Y7oWuIVYooHKmwvwRB2RxXc/eCz9mqsfScTbcCkx69i0Y2CFbfbf3dIXuaYsOoxIP/JmBfVhryp1maeR5rquj4ptXKKOTK44KZB3RkgRqNVFWnUEC9fgkRzVYvMnyowKUNesaNgBpVDW2aLZ1kRoTD2ri1BmtVw7zRW/ixcWcGnwEfvP0/eqBZA8VVsGvgfhhfd1a7ZnYOvMYen8xvzjC7OUCONjOeFirhDHmzLr6lF0Op1RoVBSL6EJYO/6T5e37S7xmjYvBtd3//ZPFjN+3aNR54H14QZQKvcjzuIJBFU1g6CBhjU73UGLxOu5zVpa9XecZQ/r3rydKV8V2fRsiBxBjF9EGFI1enwVd+ErzotPOw3HNGoaRhSBhhbuZmIihVIYE9s+m+LvfDPd4upWW3LN+cAapHDvR4lIwhAyUDkXgniSrUZ1RfYp4uPUa8yQlq/oIYRF4jajQjJ9sKkgs7BjH2fQD6pn+h+40HOqLoY9TvsdXnsLO4DQxQJwC+XD/BRJ1ncMZW8JMQGe6FEHXns+7mgT7CHSexNfkp4TjBrYoEmerrVVesg="
    - secure: "BBpF4YNz4RxyKZO2jZ0anO0GVWV/Jwutvs9a0NfTsFuEQ0VVSRNMJ3787TUzKbwo1J+nt6gn2Ag2u7FyveFGVkj5sF4hwP+GRG7UUV0IJOmhcN/41yig/uSwFWmTa+MNX1sQnZ7Ku8h6Dbb1rBRgk6YVLSlxNDB42LjzBe1Tdzvc/YjKyd3yPVo2t13nf/mixRNakeFSfihCawsmTVHgUV3GztjUPmllz+vAD/9L1HQu3OJS8ZEzghLwH0q27dShcypNCPoOaIxWYB7hGwGcEMcQtZkhhY/gBnxYBxpQ2YXM16IjRHZwJ1YdUVoowzX5YOfM+HuyJXuN/cIMk9Wym7F6Te6esMERDmQ7LT4GqHyOjfkUEw63gEt/whY8/pOkQVpTDDqeNrrLSwW7fcOi88coZ8qVf0EaHoBsfnFd3o7ONrETKdwDEt/qr3h6V8JLvUqmGzAXThAeea3ybPhWkO0tO5YyFnFnm06rt1HVig/x0EzHuR76q3B0n75y+F0kSYBlxsAknttScVDYKK9ohkP1R42t/JDWFDhczpsCIw0d7UzPbV55D719LXSU+0JQxJ4SgdjVgZemrCQvDPJM7tSdLgBNFwmPnqG43sRyZ9+tBqZ0MLUJae5+ekOIlY7+gaJpSKLLqeA5e42+0ZhTJelGlKCE8oS/WZL6UNIwlDY="
    - secure: "lyOduDN+vAc2wAcpI6H20xn4NRgXjLHcap1qEtAPnZhc1vmNjN4U+1VWOGPPbc1MwxTR0hJs5aOOT+hJvkt7NCCAbnA0/7UdF263pbkOmT/ntP6XMLMfCl6bOlnAIO7Atx7N/pey1bON5t0SbOwyd4YXu/vKmAPmxedcelzUYcS6JkRqKktAe2cl7SxSf/3oBf8cAa5k4ou6IYVnHjzg/ABqzyNAElm4tiQq4EGvFvEIihVbzawGYZJkDKTUomWmflTe3ybq4QVlLqBJJUedH7uLrZG/BX/uMfCYfMcJDN8+xcTx87PGnO72WXYrzu/KXrptO5Hf8owPPYAj8XAgZPHvGCApeFeUQqzkGaGUHPbDQBOqb7fhTNsZbmrKcAozaY9pbnbQvfsLPpYi1nRBKG7Rml3d6U4g9ZQM0cD4F4jBpOQYA17P0zRVdNztikI42y5ReG8E4RvwVUlN5W8Ir99UCGd9Iuj+juvwwkDBjg9bh1t/bCLb2CJQ1aaSoMdWG0obG6OQxRB2MTY8r2NdgDo1d5MNcNXhPPX3z9IKN17S6JEzrQ7NwPrXy4UMHNlU6yKLhAgXFSvyd+eawNI6EhiaJHDFjHTSh/rHW4z6q3fVmgZyW24gu3EGHXMNuyvqcvbxrkrhWRoiC+ImE5Zbna8UjAQ+jjFZ7heHYlFGG+8="

deploy:
  provider: azure_web_apps
  on: branch_bot_eki